### ISSUE TITLE
哇！怎么能没有王福朋老师的《深入理解 JavaScript 原型与闭包》

### ISSUE THREAD

**Issue by ZavierTang** [stephentian/33-js-concepts#23]
系列文章地址：https://www.cnblogs.com/wangfupeng1988/p/3977924.html

这一系列文章看完，对原型、原型链、作用域闭包等知识点的认识简直大彻大悟呀，下面附上文章开篇说明：

> 该教程绕开了javascript的一些基本的语法知识，直接讲解javascript中最难理解的两个部分，也是和其他主流面向对象语言区别最大的两个部分——原型和闭包，当然，肯定少不了原型链和作用域链。帮你揭开javascript最神秘的面纱。
> 
> 为什么要偏偏要讲这两个知识点？
> 
> 这是我在这么多年学习javascript的经历中，认为最难理解、最常犯错的地方，学习这两个知识点，会让你对javascript有更深层次的理解，至少理解了原型和作用域，就不能再算是javascript菜鸟了。另外，这两方面也是javascript与其他语言不同的地方，学习这样的设计，有助于你开阔眼界，帮助你了解编程语言的设计思路。毕竟，你不能只把眼睛盯在一门语言上。
> 
> 闲话不多讲，相信奔着这个话题来的朋友，也知道javascript原型和作用域的重要性。
> 
> 最后说明：被系列教程我不是照搬的其他图书或者网络资料，而是全凭着我对知识的理解而一步一步写的。思路也是我一边写着一边想的。有什么不对的地方，欢迎指正。

**Comment by stephentian** [comment]
赞，添加了，谢谢
