### ISSUE TITLE
Pull Request to leonardomso/33-js-concepts?

### ISSUE THREAD

**Issue by karlhorky** [stephentian/33-js-concepts#3]
Hello, thanks for making this!

Would it be possible to make this into a pull request to the [`leonardomso/33-js-concepts`](https://github.com/leonardomso/33-js-concepts) library so that all languages can stay in the same place?

It could be under a shared organization, if credit / acknowledgement / recognition should be shared.

cc @leonardomso

**Comment by leonardomso** [comment]
I think that we could add on the repo in English a section to all others repos in other languages. Would be very helpful for those who don't speak English. Also, would be an incentive for those who want to translate the repo for it's own language. What you think?

**Comment by karlhorky** [comment]
That would be another way to go about it, sure.

However, having it in one repository would have some benefits:

- pull requests could update multiple languages all at once
- versions could be released simultaneously
- languages could be marked as "stale" more easily when they get out of date

Probably others that I'm not thinking about right now too.

But if you don't want the management overhead, can totally understand keeping them separate.

**Comment by leonardomso** [comment]
Thinking in a long term, that would be really nice, I really gonna think about it 🤔

**Comment by stephentian** [comment]
That's a good idea.
I'll pull request to the [leonardomso/33-js-concepts](https://github.com/leonardomso/33-js-concepts) library.
It will make you more famous among Chinese developers

**Comment by karlhorky** [comment]
@stephentian I assume it was this PR here: leonardomso/33-js-concepts#41 

Would you be open to instead moving the readme into a shared repository (where you would become a maintainer)?

**Comment by stephentian** [comment]
Okay, let's wait for leonardomso's oponion

**Comment by karlhorky** [comment]
Cool, let us know when you've had a chance to think about it @leonardomso .

**Comment by karlhorky** [comment]
Otherwise this issue can be closed because leonardomso/33-js-concepts#41 was merged.

**Comment by karlhorky** [comment]
Ah, I didn't mean that you should close it right away @stephentian.

I meant it can be closed in case @leonardomso decides he doesn't want to merge the repositories for some reason.

**Comment by leonardomso** [comment]
I talked with @karlhorky in Twitter, for now, I don't think that makes sense we make a shared organization because all the articles are written in English, except for the Chinese translation (you guys have a lot of JS material in Chinese).

But as I said, this is just the beginning of the idea, maybe in the future, we could totally make this a shared organization and add more content, make some repos specified like "33 Concepts about Node.js" or something like that.
